Adds Contibuting.md file
PyTorchLightning/pytorch-lightning-bolts pull request #250
Opened 2020-09-24 03:16 UTC by oke-aditya

# Before submitting
Closes #212 
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?

Adds `contributing.md` file as discussed. Most contributing file is same as lightning. 
Line 97 introduces an extra section of `New Models` which can be added.

Please let me know what needs to be added more or removed from the current file.

## PR review    
Need review from all 👍 

## Did you have fun?
Had fun, but no coding here. But next time definitely will code.

2020-09-24 03:17 UTC, oke-aditya commented on .github/CONTRIBUTING.md
> +### New Models:
This is the only new section

2020-09-24 03:18 UTC, oke-aditya commented on .github/CONTRIBUTING.md
> +### Test cases:
I guess this should be edited. Let me know what should go in here if needed.

2020-09-24 08:30 UTC, Borda requested changes
it seems that there not many specific sections and some text is very unrelated to Bolts...
I have removed some but could you please prune it more and refer to the PL contributing as needed, it would be for us much easier to maintain only one main contribution guide and in other "supplementary" projects have only specific updates

2020-09-24 11:45 UTC, oke-aditya commented
Absolutely it isn't good to repeat and it might become too much read for user. I will try to prune further.

Do let me know how tests are written here which are different from lightning.

2020-09-24 14:08 UTC, Borda commented
> Do let me know how tests are written here which are different from lightning.

the tests are the same, just moreover we shall add testing scripts with some arguments parsing...

2020-09-26 17:05 UTC, Borda commented on .github/CONTRIBUTING.md
> +   All help is extremely welcome - reporting bugs, fixing documentation, adding test cases, solving issues and preparing bug fixes. To solve some issues you can start with label [good first issue](ht
update these links to Bolts

2020-09-26 17:12 UTC, oke-aditya commented on .github/CONTRIBUTING.md
> +   All help is extremely welcome - reporting bugs, fixing documentation, adding test cases, solving issues and preparing bug fixes. To solve some issues you can start with label [good first issue](ht
Updated 👍

2020-10-22 17:35 UTC, Borda approved these changes

2020-10-22 17:35 UTC, merged