Feature/489 update tensorboard generative model image sampler args
PyTorchLightning/pytorch-lightning-bolts pull request #494
Opened 2021-01-04 13:00 UTC by chris-clem

## What does this PR do?
Updates TensorboardGenerativeModelImageSampler args as discussed in #489.

Fixes #489 489

## Before submitting
- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? [not needed for typos/docs]
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/CHANGELOG.md)?

## PR review
 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2021-01-05 08:16 UTC, akihironitta requested changes
@chris-clem Thank you for your swift action! Would you mind having a look at the below suggestions?

2021-01-05 08:16 UTC, akihironitta commented on pl_bolts/callbacks/vision/image_generation.py
> +            pad_value: Value for the padded pixels. Default: ``0``.
Could you add `num_samples` to the docstring?

2021-01-05 08:16 UTC, akihironitta commented on pl_bolts/callbacks/vision/image_generation.py
> +            normalize: If True, shift the image to the range (0, 1),
```suggestion
            normalize: If ``True``, shift the image to the range (0, 1),
```

2021-01-07 10:49 UTC, akihironitta commented
@Borda @ananyahjha93 Should we include the tests for this class in this PR? or later in another PR?

2021-01-18 08:52 UTC, Borda approved these changes

2021-01-18 08:55 UTC, merged